name: test-snap-ros2-eloquent
version: "0.1"
summary: Eloquent ROS2 Example
description: |
 A ROS2 workspace containing a talker and a listener.
 
grade: devel
confinement: strict
base: core18
 
parts:
 colcon-part:
   plugin: colcon
   source: https://github.com/ros2/demos.git
   source-branch: eloquent
   colcon-rosdistro: eloquent
   colcon-source-space: demo_nodes_cpp
   build-packages: [make, gcc, g++]
   stage-packages: [ros-eloquent-ros2launch]
 
apps:
 eloquent-talker-listener-arnatious:
   command: opt/ros/eloquent/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
   plugs: [network, network-bind]
